<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Oscar Flores y Rodrigo Martinez

**Fecha:** 16 de febrero de 2021

**Expediente** : 715029 y 
**Profesor:** Oscar David Jaramillo Zuluaga.

**Link Github:** https://github.com/OscarFlores-IFi/SPF-2021-Tareas

# Tarea 4: Clase 7

# Tarea

# 1
Como ejemplo simple de una simulación de Monte Carlo, considere calcular la probabilidad de una suma particular del lanzamiento de tres dados (cada dado tiene valores del uno al seis). Además cada dado tiene las siguientes carácterísticas: el primer dado no está cargado (distribución uniforme todos son equiprobables); el segundo y tercer dado están cargados basados en una distribución binomial con parámetros (`n=5, p=0.5` y `n=5, p=0.2`). Calcule la probabilidad de que la suma resultante sea 7, 14 o 18. 

#### Solucion Oscar 

In [106]:
import scipy.stats as st
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from functools import reduce

def no_cargados(size = 10000):
    return np.random.randint(1, 7, size = size)

def cargados(n=5, p=0.5, size = 10000):
    return st.binom(n=n, p=p).rvs(size=size) + 1

def varios_dados(func, dados = 3, **kwargs):
    simulaciones = [dado_cargado( **kwargs ) for i in range(dados)]
    return reduce(lambda a,b: a+b, simulaciones)

0.0853

In [129]:
# no cargado: 
size = 100000

pd.value_counts(varios_dados(no_cargados, size = 100000))/size # distribución de cada suma de dados

# suma acumulada: 0.08435

10    0.19590
11    0.19585
12    0.15164
9     0.15160
8     0.09320
13    0.09201
7     0.04247
14    0.04183
15    0.01456
6     0.01389
16    0.00320
5     0.00296
17    0.00041
4     0.00038
18    0.00005
3     0.00005
dtype: float64

In [131]:
# cargado n=5, p=0.5: 
size = 100000

pd.value_counts(varios_dados(cargados,  n=5, p=0.5, size = 100000))/size # distribución de cada suma de dados

# suma acumulada: 0.08389

10    0.19710
11    0.19621
12    0.15426
9     0.15076
13    0.09192
8     0.09093
7     0.04220
14    0.04162
15    0.01384
6     0.01370
5     0.00337
16    0.00317
17    0.00042
4     0.00041
18    0.00007
3     0.00002
dtype: float64

In [135]:
# cargado n=5, p=0.2: 
size = 100000

pd.value_counts(varios_dados(cargados,  n=5, p=0.2, size = 100000))/size # distribución de cada suma de dados

# suma acumulada: 0.18792

6     0.25018
5     0.22880
7     0.18981
4     0.13190
8     0.10214
9     0.04286
3     0.03608
10    0.01372
11    0.00383
12    0.00059
13    0.00008
14    0.00001
dtype: float64

#### Solucion Rodrigo

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import scipy.stats as st

In [2]:
nocargado = np.random.randint(1,7,1000)
cargado = st.binom(n=5, p=.5).rvs(size=1000)
cargado2 = st.binom(n=5, p=.2).rvs(size=1000)

todos = nocargado + cargado + cargado2

In [3]:
def juego(num):
    num = num
    if num == 7 or num == 14 or num == 18:
        return 1
    else:
        return 0

juegos = [juego(i) for i in todos]
juegos
sum(juegos)/1000

0.156

In [53]:
# Solución


(0.127, 0.01352, 1e-05)

# 2 Ejercicio de aplicación- Cafetería Central

Premisas para la simulación:
- Negocio de alimentos que vende bebidas y alimentos.
- Negocio dentro del ITESO.
- Negocio en cafetería central.
- Tipo de clientes (hombres y mujeres).
- Rentabilidad del 60%.

## Objetivo
Realizar una simulación estimado el tiempo medio que se tardaran los clientes en ser atendidos entre el horario de 6:30 a 1 pm. Además saber el consumo. 
**Analizar supuestos y limitantes**

## Supuestos en simulación
Clasificación de clientes: 
- Mujer  = 1 $\longrightarrow$ aleatorio < 0.5
- Hombre = 0 $\longrightarrow$ aleatorio $\geq$ 0.5.

Condiciones iniciales:
- Todas las distrubuciones de probabilidad se supondrán uniformes.
- Tiempo de simulación: 6:30 am - 1:30pm $\longrightarrow$ T = 7 horas = 25200 seg.
- Tiempo de llegada hasta ser atendido: Min=5seg, Max=30seg.
- Tiempo que tardan los clientes en ser atendidos:
    - Mujer: Min = 1 min= 60seg, Max = 5 min = 300 seg
    - Hombre: Min = 40 seg, Max = 2 min= 120 seg
- Consumo según el tipo de cliente:
    - Mujer: Min = 30 pesos, Max = 100 pesos
    - Hombre: Min = 20 pesos, Max = 80 pesos

Responder las siguientes preguntas basados en los datos del problema:
1. ¿Cuáles fueron los gastos de los hombres y las mujeres en 5 días de trabajo?.
2. ¿Cuál fue el consumo promedio de los hombres y mujeres?
3. ¿Cuál fue el número de personas atendidas por día?
4. ¿Cuál fue el tiempo de atención promedio?
5. ¿Cuánto fue la ganancia promedio de la cafetería en 5 días de trabajo y su respectiva rentabilidad?

In [137]:
################## Datos del problema
d = 5
T =25200
T_at_min = 5; T_at_max = 30
T_mujer_min =60; T_mujer_max = 300
T_hombre_min = 40; T_hombre_max = 120
C_mujer_min = 30; C_mujer_max = 100
C_hombre_min = 20; C_hombre_max = 80


#### Solucion Oscar 

Como primer supuesto es que, debido a que todas las variables son independientes, podemos simular distintos parametros por separado y no cambia el resultado final que si se simulan todos los escenarios simultaneamente. No obstante, el primero de los métodos es un poco más eficiente debido a que permite la vectorización en algunos de los parámetros.

Otro de los supuestos permite que se atienda cierta cantidad de personas simultáneamente, sin embargo, no se considera el calculo de el máximo de personas atendidas simúltaneamente en el ejercicio, ni el tiempo máximo en el que se dejarían de recibir pedidos (si se llega a la 1:29:55 se le atendería aunque el tiempo de atenderlo sea de 5 min.)

In [214]:
import numpy as np

def atendidos_un_dia(t = 25200):
    cant_clientes = 0
    tiempos = []
    while t > 0: 
        t_at = np.random.randint(T_at_min, T_at_max)
        t -= t_at

        tiempos.append(t_at)
    return tiempos

def genero(x):
    return 1 if np.random.rand() < 0.5 else 0 # Asumamos para este caso que hombre es 1 y mujer es 0 

def consumo(x):
    return np.random.randint(C_mujer_min, C_mujer_max) if x == 1 else np.random.randint(C_hombre_min, C_hombre_max)

def tiempo_atencion(x):
    return np.random.randint(T_mujer_min, T_mujer_max) if x == 1 else np.random.randint(T_hombre_min, T_hombre_max)


# Personas atendidas en un día particular: 
# atendidos_hoy = atendidos_un_dia()

# Genero de las personas atendidas en ese día: 
# genero_atendidos = list(map(genero, np.zeros(len(atendidos_hoy))))

# Consumo por persona en ese día: 
# consumo_atendidos = list(map(consumo, genero_atendidos))

# Tiempo en ser atendidos en ese día:
# tiempo_atendidos = list(map(tiempo_atencion, genero_atendidos))



# ¿Cuáles fueron los gastos de los hombres y las mujeres en 5 días de trabajo?.
# ¿Cuál fue el consumo promedio de los hombres y mujeres?
# ¿Cuál fue el número de personas atendidas por día?
# ¿Cuál fue el tiempo de atención promedio?
# ¿Cuánto fue la ganancia promedio de la cafetería en 5 días de trabajo y su respectiva rentabilidad?



atendidos_dia = []

gastos = np.zeros(5)
consumo_promedio_mujeres = np.zeros(5)
consumo_promedio_hombres = np.zeros(5)
personas_por_dia_hombres = np.zeros(5)
atencion_promedio = np.zeros(5)
ganancia_promedio = np.zeros(5)
for i in range(5):
    atendidos_dia.append(atendidos_un_dia())
    genero_atendidos = np.array(list(map(genero, np.zeros(len(atendidos_dia[-1])))))
    
    gastos[i] = np.sum(list(map(consumo, genero_atendidos)))
    consumo_promedio_mujeres[i] = np.mean(list(map(consumo, genero_atendidos[genero_atendidos ==1])))
    consumo_promedio_hombres[i] = np.mean(list(map(consumo, genero_atendidos[genero_atendidos ==0])))
    atencion_promedio[i] = np.mean(list(map(tiempo_atencion, genero_atendidos)))
    ganancia_promedio[i] = gastos[i]*0.6

    

In [215]:
# Gastos díarios de hombres y mujeres: 
gastos

array([83735., 86641., 83219., 84813., 86873.])

In [216]:
# Consumo promedio de hombres :
consumo_promedio_hombres

array([48.74655647, 50.19428571, 48.98497268, 48.78025035, 49.64768212])

In [217]:
# Consumo promedio de mujeres: 
consumo_promedio_mujeres

array([62.52736983, 63.72439949, 64.41032609, 64.55287818, 63.46499339])

In [218]:
# Atendidos por día: 
list(map(lambda x: len(x), atendidos_dia))

[1475, 1491, 1468, 1466, 1512]

In [219]:
# Tiempo de atención promedio: 
atencion_promedio

array([129.52881356, 132.0878605 , 131.35899183, 130.59208731,
       129.35648148])

In [220]:
# Ganancia promedio: 
ganancia_promedio

array([50241. , 51984.6, 49931.4, 50887.8, 52123.8])

#### Solucion Rodrigo

In [4]:
################## Datos del problema
d = 5
T =25200
T_at_min = 5; T_at_max = 30
T_mujer_min =60; T_mujer_max = 300
T_hombre_min = 40; T_hombre_max = 120
C_mujer_min = 30; C_mujer_max = 100
C_hombre_min = 20; C_hombre_max = 80

In [5]:
def cafeteria():
    tiempo = []
    llegada = []
    sex=[]
    consumo=[]
    while sum(tiempo) + sum(llegada) < T * d:
        llegada.append(np.random.uniform(5,30))
        g = np.random.uniform(0,1)
        if g < 0.5:
            sexo = 'mujer'
        else:
            sexo = 'hombre'
        sex.append(sexo)
        
        if sexo == 'mujer':
            tiempo.append(np.random.uniform(60,300))
            consumo.append(np.random.uniform(30,100))
        else:
            tiempo.append(np.random.uniform(40,120))
            consumo.append(np.random.uniform(20,80))
            
    x = pd.DataFrame(data={'sexo': sex, 'tiempo': tiempo, 'llegada': llegada, 'consumo': consumo})
    return x

cafe = cafeteria()

cafe.head()

sexo      tiempo    llegada    consumo
0   mujer  161.242827  25.389995  73.502004
1   mujer  210.582289  17.538786  50.164101
2  hombre   74.095911   9.171240  44.861488
3  hombre   51.220232   6.290292  50.065216
4  hombre  105.115777   9.177351  42.024168

In [6]:
# 1. ¿Cuáles fueron los gastos de los hombres y las mujeres en 5 días de trabajo?.
cafe['consumo'].sum()

49170.945253833954

In [7]:
# 2. ¿Cuál fue el consumo promedio de los hombres y mujeres?
hombres = cafe[cafe['sexo'] == 'hombre']
hombres['consumo'].sum() / len(hombres)

51.0674705142125

In [8]:
mujeres = cafe[cafe['sexo'] == 'mujer']
mujeres['consumo'].sum() / len(mujeres)

64.89176427191336

In [9]:
# 3. ¿Cuál fue el número de personas atendidas por día?
len(cafe) / 5

169.4

In [10]:
# 4. ¿Cuál fue el tiempo de atención promedio?
cafe['tiempo'].mean()

131.49647877235282

In [11]:
# 5. ¿Cuánto fue la ganancia promedio de la cafetería en 5 días de trabajo y su respectiva rentabilidad?
cafe['consumo'].sum() * 0.6

29502.56715230037

In [12]:
cafe['consumo'].sum() * 0.6 / cafe['consumo'].sum()

0.6